// Generated by gencpp from file concatsrv/ConCatRequest.msg
// DO NOT EDIT!


#ifndef CONCATSRV_MESSAGE_CONCATREQUEST_H
#define CONCATSRV_MESSAGE_CONCATREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace concatsrv
{
template <class ContainerAllocator>
struct ConCatRequest_
{
  typedef ConCatRequest_<ContainerAllocator> Type;

  ConCatRequest_()
    : first()
    , second()  {
    }
  ConCatRequest_(const ContainerAllocator& _alloc)
    : first(_alloc)
    , second(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _first_type;
  _first_type first;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _second_type;
  _second_type second;




  typedef boost::shared_ptr< ::concatsrv::ConCatRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::concatsrv::ConCatRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConCatRequest_

typedef ::concatsrv::ConCatRequest_<std::allocator<void> > ConCatRequest;

typedef boost::shared_ptr< ::concatsrv::ConCatRequest > ConCatRequestPtr;
typedef boost::shared_ptr< ::concatsrv::ConCatRequest const> ConCatRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::concatsrv::ConCatRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::concatsrv::ConCatRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace concatsrv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::concatsrv::ConCatRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::concatsrv::ConCatRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::concatsrv::ConCatRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::concatsrv::ConCatRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::concatsrv::ConCatRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::concatsrv::ConCatRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::concatsrv::ConCatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0d0db6e21f3fc1eb068f9cc22ba8beb";
  }

  static const char* value(const ::concatsrv::ConCatRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0d0db6e21f3fc1eULL;
  static const uint64_t static_value2 = 0xb068f9cc22ba8bebULL;
};

template<class ContainerAllocator>
struct DataType< ::concatsrv::ConCatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "concatsrv/ConCatRequest";
  }

  static const char* value(const ::concatsrv::ConCatRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::concatsrv::ConCatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string first\n\
string second\n\
";
  }

  static const char* value(const ::concatsrv::ConCatRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::concatsrv::ConCatRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.first);
      stream.next(m.second);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConCatRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::concatsrv::ConCatRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::concatsrv::ConCatRequest_<ContainerAllocator>& v)
  {
    s << indent << "first: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.first);
    s << indent << "second: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.second);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONCATSRV_MESSAGE_CONCATREQUEST_H
