// Generated by gencpp from file concatsrv/ConCat.msg
// DO NOT EDIT!


#ifndef CONCATSRV_MESSAGE_CONCAT_H
#define CONCATSRV_MESSAGE_CONCAT_H

#include <ros/service_traits.h>


#include <concatsrv/ConCatRequest.h>
#include <concatsrv/ConCatResponse.h>


namespace concatsrv
{

struct ConCat
{

typedef ConCatRequest Request;
typedef ConCatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConCat
} // namespace concatsrv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::concatsrv::ConCat > {
  static const char* value()
  {
    return "02a66ab9a58339fab12650d18b17ba68";
  }

  static const char* value(const ::concatsrv::ConCat&) { return value(); }
};

template<>
struct DataType< ::concatsrv::ConCat > {
  static const char* value()
  {
    return "concatsrv/ConCat";
  }

  static const char* value(const ::concatsrv::ConCat&) { return value(); }
};


// service_traits::MD5Sum< ::concatsrv::ConCatRequest> should match 
// service_traits::MD5Sum< ::concatsrv::ConCat > 
template<>
struct MD5Sum< ::concatsrv::ConCatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::concatsrv::ConCat >::value();
  }
  static const char* value(const ::concatsrv::ConCatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::concatsrv::ConCatRequest> should match 
// service_traits::DataType< ::concatsrv::ConCat > 
template<>
struct DataType< ::concatsrv::ConCatRequest>
{
  static const char* value()
  {
    return DataType< ::concatsrv::ConCat >::value();
  }
  static const char* value(const ::concatsrv::ConCatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::concatsrv::ConCatResponse> should match 
// service_traits::MD5Sum< ::concatsrv::ConCat > 
template<>
struct MD5Sum< ::concatsrv::ConCatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::concatsrv::ConCat >::value();
  }
  static const char* value(const ::concatsrv::ConCatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::concatsrv::ConCatResponse> should match 
// service_traits::DataType< ::concatsrv::ConCat > 
template<>
struct DataType< ::concatsrv::ConCatResponse>
{
  static const char* value()
  {
    return DataType< ::concatsrv::ConCat >::value();
  }
  static const char* value(const ::concatsrv::ConCatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONCATSRV_MESSAGE_CONCAT_H
